### ISSUE TITLE
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

### ISSUE THREAD

**Issue by durika** [laviavigdor/twitter-sentiment-analysis#3]
I get following error trying to train the model:

C:\Users\JK186034\Documents\Py\sentiment> python train.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    main()
  File "train.py", line 39, in main
    word_index, x_train, x_val, y_train, y_val = get_training_and_validation_set
s()
  File "train.py", line 49, in get_training_and_validation_sets
    X_raw, Y_raw = load_data_set()
  File "train.py", line 140, in load_data_set
    for i, line in enumerate(reader):
_csv.Error: iterator should return strings, not bytes (did you open the file in
text mode?)

I am running this on anaconda under windows:
C:\Users\JK186034\Documents\Py\sentiment>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by durika** [comment]
nevermind this one

**Comment by anjasopo** [comment]
me too
